<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>NotepadEncrypt</AssemblyName>
    <ApplicationIcon>artwork\Icon.ico</ApplicationIcon>
    <PackageIcon>NotepadEncrypt.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="artwork\Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="artwork\Icon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="artwork\NotepadEncrypt.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
